name: run main.py

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run script
        run: python main.py > "$(date +"%Y_%m_%d_%I_%M_%p").md"
      
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
      - name: Set up commit 
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "New Todo for output"
          git push origin master
      
      - name: create pull request
        run: gh pr create -B base_branch -H branch_to_merge --title 'Routine' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ github.token }}
