name: run main.py

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run script
        run: python main.py > todo.md 
      
      - name: create pull request
        run: gh pr create -B base_branch -H branch_to_merge --title 'Routine' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ github.token }}
